# Generated by Django 5.0.4 on 2024-05-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
    ]
